// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"golang.org/x/sync/errgroup"
	"week04/app/book/internal/conf"
	"week04/app/book/internal/server"
)

// Injectors from wire.go:

// initApp Inject wire ProvideSet
func initApp(group *errgroup.Group, option conf.Options) *App {
	engine := server.NewHttpRouter(option)
	httpServer := server.NewHttpServer(group, option, engine)
	grpcServer := server.NewGRPCServer(group, option)
	app := newApp(httpServer, grpcServer)
	return app
}

// wire.go:

type App struct {
	HttpServer *server.HttpServer
	GRPCServer *server.GRPCServer
}

// newApp return App struct with server.HttpServer and server.GRPCServer
func newApp(http *server.HttpServer, grpc *server.GRPCServer) *App {
	return &App{HttpServer: http, GRPCServer: grpc}
}
