// Code generated by entc, DO NOT EDIT.

package ent

import (
	"week04/app/book/internal/data/ent/book"
	"week04/app/book/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	bookFields := schema.Book{}.Fields()
	_ = bookFields
	// bookDescName is the schema descriptor for name field.
	bookDescName := bookFields[0].Descriptor()
	// book.DefaultName holds the default value on creation for the name field.
	book.DefaultName = bookDescName.Default.(string)
	// bookDescAuthor is the schema descriptor for author field.
	bookDescAuthor := bookFields[1].Descriptor()
	// book.DefaultAuthor holds the default value on creation for the author field.
	book.DefaultAuthor = bookDescAuthor.Default.(string)
	// bookDescNumber is the schema descriptor for number field.
	bookDescNumber := bookFields[2].Descriptor()
	// book.DefaultNumber holds the default value on creation for the number field.
	book.DefaultNumber = bookDescNumber.Default.(int)
}
